services:
  - type: web
    name: kblog-backend
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server/index.js
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://kblog_admin:KBlogProd2026SecureDbPass99@kblogcluster.prqftm8.mongodb.net/kblog?retryWrites=true&w=majority&appName=KBlogCluster
      - key: JWT_SECRET
        value: supersecretjwtkey
      - key: CLOUDINARY_CLOUD_NAME
        value: dhwdcmmwa
      - key: CLOUDINARY_API_KEY
        value: 927742949392543
      - key: CLOUDINARY_API_SECRET
        value: ahg_in0hF20mN3XdkJwnC0geubQ
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: FROM_NAME
        value: "Chills App"
      - key: FROM_EMAIL
        sync: false
      - key: FRONTEND_URL
        sync: false
